spring:
  config:
    import: classpath:.env.properties

  data:
    mongodb:
      uri: ${DB_URL}
      port: ${DB_PORT}
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PWD}

  application:
    name: chatserver


jwt-secret: ${JWT_SECRET}