import { ProductItemProps } from "@/shared/types/product";

export const dummyProducts: ProductItemProps[] = [
  {
    id: 101,
    title: "중고 골프채 세트 팝니다",
    price: 120000,
    region: "경기도 의왕시",
    categoryName: "스포츠/레저",
    thumbnailUrl: "/thumbnail1.jpg",
    status: "AVAILABLE",
    createdAt: "2025-05-18T10:00:00",
    viewCount: 23,
    favoriteCount: 3,
    authorNickname: "golfking",
    isLiked: false,
    latitude: 37.3625,
    longitude: 126.9750,
  },
  {
    id: 102,
    title: "의왕시 책상 판매합니다",
    price: 30000,
    region: "경기도 의왕시",
    categoryName: "가구",
    thumbnailUrl: "/thumbnail2.jpg",
    status: "AVAILABLE",
    createdAt: "2025-05-17T14:30:00",
    viewCount: 48,
    favoriteCount: 7,
    authorNickname: "desklover",
    isLiked: false,
    latitude: 37.3608,
    longitude: 126.9795,
  },
  {
    id: 103,
    title: "자전거 팝니다 (의왕시 직거래)",
    price: 90000,
    region: "경기도 의왕시",
    categoryName: "레저",
    thumbnailUrl: "/thumbnail3.jpg",
    status: "AVAILABLE",
    createdAt: "2025-05-16T08:15:00",
    viewCount: 19,
    favoriteCount: 1,
    authorNickname: "bikerider",
    isLiked: false,
    latitude: 37.3595,
    longitude: 126.9822,
  },
];
